# Generated by Django 3.2.6 on 2021-08-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='undergrad_or_grad',
            new_name='account_type',
        ),
    ]
