# Generated by Django 3.2.6 on 2021-08-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublications',
            name='display',
            field=models.CharField(blank=True, choices=[('display', 'Display'), ('noDisplay', 'Do not display')], max_length=200, null=True),
        ),
    ]
