# Generated by Django 3.2.6 on 2021-08-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210816_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublications',
            name='journal_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
