# Generated by Django 3.2.6 on 2021-08-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userpublications_journal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
