# Generated by Django 3.2.6 on 2021-08-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='profiles/'),
        ),
    ]
