# Generated by Django 3.2.6 on 2021-08-22 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='occupation',
            new_name='area_of_interest',
        ),
    ]
