# Generated by Django 3.2.6 on 2021-08-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_occupation_profile_area_of_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('undergrad', 'Undergraduate'), ('grad', 'Graduate'), ('invisible', 'Invisible'), ('post', 'Postdocs'), ('res', 'Research Staff'), ('alum', 'Alumni')], max_length=300, null=True),
        ),
    ]
