# Generated by Django 3.2.6 on 2021-08-26 01:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserSkills',
        ),
    ]
