# Generated by Django 3.2.6 on 2021-08-26 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210825_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skills',
            new_name='skills_and_ongoing_projects',
        ),
    ]
