# Generated by Django 3.2.6 on 2021-08-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_skills_profile_skills_and_ongoing_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublications',
            name='only_enter_year_xxxx',
            field=models.IntegerField(null=True),
        ),
    ]
