# Generated by Django 3.2.6 on 2021-08-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_userpublications_only_enter_year_xxxx'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='profiles/'),
        ),
    ]
