# Generated by Django 3.2.6 on 2021-08-26 15:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_text', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
