# Generated by Django 3.2.6 on 2021-08-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometext',
            name='home_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
